import Providers from '@/utils/provider'

import './globals.css'
import { Inter } from 'next/font/google'

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chat app by Liam',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div>
            <Providers>{children}</Providers>
            <ToastContainer />
          </div>
        </main>
      </body>
    </html>
  )
}
